export const REVIEWS = [
  {
    id: 1,
    name: "JUDY",
    avatar: "/images/review-judy.jpg",
    stars: 5,
    text: "I'm taking Marah Cel for osteoporosis and have already noticed better sleep. My consultation with Eunice was very helpful – she answered my questions and provided useful follow-up resources.",
    date: "01/24/2025",
  },
  {
    id: 2,
    name: "MICHELLE",
    avatar: "/images/review-michelle.jpg",
    stars: 5,
    text: "It helps me stay healthy, supports my overall wellness, keeps me active and energized throughout the day, improves my quality of life, and ensures my bones remain strong and healthy continue to age gracefully.",
    date: "01/24/2025",
  },
  {
    id: 3,
    name: "OLGA",
    avatar: "/images/review-olga.jpg",
    stars: 5,
    text: "I sincerely recommend your products. They are high-quality, reliable, and made with trusted ingredients, delivering consistent results that I can confidently stand behind.",
    date: "11/04/2024",
  },
  {
    id: 4,
    name: "BARBARA",
    avatar: "/images/review-barbara.jpg",
    stars: 5,
    text: "Been using this for 3 months now. Great results – my skin feels calmer, more hydrated, and my overall complexion looks much more radiant. It truly helps with my confidence.",
    date: "01/22/2025",
  },
  {
    id: 5,
    name: "LINDA",
    avatar: "/images/review-linda.jpg",
    stars: 5,
    text: "Absolutely love this product! My energy levels have improved dramatically and I feel so much better overall. I have recommended it to all my friends and family already.",
    date: "12/15/2024",
  },
  {
    id: 6,
    name: "PATRICIA",
    avatar: "/images/review-patricia.jpg",
    stars: 5,
    text: "This has been a game changer for me. I noticed a difference within the first two weeks. My sleep improved, my joint pain reduced, and I feel so much more energetic every day.",
    date: "02/03/2025",
  },
];
